### PR TITLE
Replace reflect.DeepEqual() with "github.com/google/go-cmp/cmp"

### PR DESCRIPTION
**Pull request by infiniteoverflow**
Issue URL : https://github.com/openebs/openebs/issues/3143

### CODE REVIEW

**Comment by shubham14bajpai** [comment]
@infiniteoverflow travis is failing due to import errors. Please add import for cmp and remove reflect.

**Comment by infiniteoverflow** [comment]
> @infiniteoverflow travis is failing due to import errors. Please add import for cmp and remove reflect.

@shubham14bajpai  I have made the changes as requested.

**Review by prateekpandey14 — APPROVED** [review]
lgtm

**Comment by shubham14bajpai** [comment]
Thank you @infiniteoverflow  for this PR. You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Pull request merged**
