### PR TITLE
Update the main README with info and link upgrade & migration docs #3145

### PR DESCRIPTION
**Pull request by Naveenkhasyap**
Updating `Readme.md` with Upgrade and Migration steps from respective docs folder  issue #3145 
contents are taken from below.
[upgrade](https://github.com/openebs/upgrade/blob/master/docs/upgrade.md)
[migrate](https://github.com/openebs/upgrade/blob/master/docs/migration.md)

### CODE REVIEW

**Review by shubham14bajpai — COMMENTED** [review]
Can you please rebase and push the changes again.

**Comment by Naveenkhasyap** [comment]
> Can you please rebase and push the changes agai

ok

**Comment by Naveenkhasyap** [comment]
@shubham14bajpai can you review it now.

**Review by prateekpandey14 — APPROVED** [review]
lgtm

**Comment by prateekpandey14** [comment]
Thank you @Naveenkhasyap  for this PR. You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Pull request merged**
